require:
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
AllCops:
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
Style/Documentation:
  Enabled: false
#-------------------------------------------------------------------------------
RSpec/ExampleLength:
  Exclude:
    - spec/unit/records_handler_spec.rb
    - spec/unit/snapshots/apps/snapshot_discoverer_spec.rb
    - spec/unit/snapshots/apps/snapshot_ingester_spec.rb
    - spec/unit/snapshots/services/snapshot_downloader_spec.rb
    - spec/unit/snapshots/services/snapshot_importer_spec.rb
    - spec/unit/snapshots/services/snapshot_link_scraper_spec.rb
    - spec/unit/snapshots/services/snapshot_reader_spec.rb
    - spec/unit/streams/apps/stream_ingester_spec.rb
    - spec/unit/streams/clients/psc_stream_spec.rb
RSpec/FilePath:
  Exclude:
    - spec/register_ingester_psc.rb
    - spec/unit/records_handler_spec.rb
    - spec/unit/snapshots/apps/snapshot_discoverer_spec.rb
    - spec/unit/snapshots/apps/snapshot_ingester_spec.rb
    - spec/unit/snapshots/services/snapshot_downloader_spec.rb
    - spec/unit/snapshots/services/snapshot_importer_spec.rb
    - spec/unit/snapshots/services/snapshot_link_scraper_spec.rb
    - spec/unit/snapshots/services/snapshot_reader_spec.rb
    - spec/unit/snapshots/services/snapshot_row_processor_spec.rb
    - spec/unit/streams/apps/stream_ingester_spec.rb
    - spec/unit/streams/clients/psc_stream_spec.rb
RSpec/MessageSpies:
  Exclude:
    - spec/unit/records_handler_spec.rb
    - spec/unit/snapshots/apps/snapshot_discoverer_spec.rb
    - spec/unit/snapshots/apps/snapshot_ingester_spec.rb
    - spec/unit/snapshots/services/snapshot_downloader_spec.rb
    - spec/unit/snapshots/services/snapshot_importer_spec.rb
    - spec/unit/snapshots/services/snapshot_link_scraper_spec.rb
    - spec/unit/snapshots/services/snapshot_reader_spec.rb
    - spec/unit/streams/apps/stream_ingester_spec.rb
    - spec/unit/streams/clients/psc_stream_spec.rb
RSpec/MultipleExpectations:
  Exclude:
    - spec/unit/records_handler_spec.rb
    - spec/unit/snapshots/apps/snapshot_discoverer_spec.rb
    - spec/unit/snapshots/apps/snapshot_ingester_spec.rb
    - spec/unit/snapshots/services/snapshot_downloader_spec.rb
    - spec/unit/snapshots/services/snapshot_importer_spec.rb
    - spec/unit/snapshots/services/snapshot_link_scraper_spec.rb
    - spec/unit/snapshots/services/snapshot_reader_spec.rb
    - spec/unit/snapshots/services/snapshot_row_processor_spec.rb
    - spec/unit/streams/apps/stream_ingester_spec.rb
    - spec/unit/streams/clients/psc_stream_spec.rb
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/unit/records_handler_spec.rb
    - spec/unit/snapshots/services/snapshot_importer_spec.rb
    - spec/unit/snapshots/services/snapshot_reader_spec.rb
RSpec/NamedSubject:
  Exclude:
    - spec/unit/records_handler_spec.rb
    - spec/unit/snapshots/apps/snapshot_discoverer_spec.rb
    - spec/unit/snapshots/apps/snapshot_ingester_spec.rb
    - spec/unit/snapshots/services/snapshot_downloader_spec.rb
    - spec/unit/snapshots/services/snapshot_importer_spec.rb
    - spec/unit/snapshots/services/snapshot_link_scraper_spec.rb
    - spec/unit/snapshots/services/snapshot_reader_spec.rb
    - spec/unit/snapshots/services/snapshot_row_processor_spec.rb
    - spec/unit/streams/apps/stream_ingester_spec.rb
    - spec/unit/streams/clients/psc_stream_spec.rb
RSpec/StubbedMock:
  Exclude:
    - spec/unit/records_handler_spec.rb
    - spec/unit/snapshots/apps/snapshot_discoverer_spec.rb
    - spec/unit/snapshots/apps/snapshot_ingester_spec.rb
    - spec/unit/snapshots/services/snapshot_downloader_spec.rb
    - spec/unit/snapshots/services/snapshot_importer_spec.rb
    - spec/unit/snapshots/services/snapshot_link_scraper_spec.rb
    - spec/unit/snapshots/services/snapshot_reader_spec.rb
    - spec/unit/streams/apps/stream_ingester_spec.rb
    - spec/unit/streams/clients/psc_stream_spec.rb
RSpec/VerifiedDoubles:
  Exclude:
    - spec/unit/records_handler_spec.rb
    - spec/unit/snapshots/apps/snapshot_discoverer_spec.rb
    - spec/unit/snapshots/apps/snapshot_ingester_spec.rb
    - spec/unit/snapshots/services/snapshot_downloader_spec.rb
    - spec/unit/snapshots/services/snapshot_importer_spec.rb
    - spec/unit/snapshots/services/snapshot_link_scraper_spec.rb
    - spec/unit/snapshots/services/snapshot_reader_spec.rb
    - spec/unit/streams/apps/stream_ingester_spec.rb
    - spec/unit/streams/clients/psc_stream_spec.rb
