version: '3.7'

services:
  register_ingester_psc:
    image: register_ingester_psc:latest
    #entrypoint: "bundle exec /app/bin/ingest_streams"
    environment:
      - PSC_STREAM_API_KEY
      - BODS_S3_BUCKET_NAME
      - BODS_AWS_REGION
      - BODS_AWS_ACCESS_KEY_ID
      - BODS_AWS_SECRET_ACCESS_KEY
      - SPLIT_SNAPSHOTS_S3_PREFIX
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_PROTOCOL
      - ELASTICSEARCH_SSL_VERIFY
      - ELASTICSEARCH_PASSWORD
      - PSC_STREAM
    restart: always

  register_ingester_psc_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - 'discovery.type=single-node'
      - 'cluster.name=register-elasticsearch'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'xpack.security.enabled=false'
    ports:
      - 9200:9200
  
  register_ingester_psc_es_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - 'discovery.type=single-node'
      - 'cluster.name=register-elasticsearch'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'xpack.security.enabled=false'
    networks:
      - register_ingester_psc_test
    expose:
      - 9200

  register_ingester_psc_unittests:
    image: register_ingester_psc:latest
    environment:
      - ELASTICSEARCH_HOST=register_ingester_psc_es_test
      - ELASTICSEARCH_PASSWORD=
      - ELASTICSEARCH_PORT=9200
      - TEST=1
    links:
      - register_ingester_psc_es_test
    networks:
      - register_ingester_psc_test
    volumes:
      - '.:/app'

networks:
  register_ingester_psc_test:
